{
  "version": "1",
  "services": {
    "api": {
      "type": "web",
      "name": "movie-app-backend",
      "env": "node",
      "repo": "https://github.com/Allensamm/trailtok.git",
      "rootDir": "backend",
      "buildCommand": "npm install",
      "startCommand": "npm start",
      "plan": "free",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "NODE_OPTIONS",
          "value": "--dns-result-order=ipv4first"
        },
        {
          "key": "DATABASE_URL",
          "value": "postgresql://postgres:I4cuicui4cuicu@db.sdvikraysasolvzanixo.supabase.co:5432/postgres"
        },
        {
          "key": "TMDB_API_KEY",
          "value": "09f074c9b676bef4f5288393ce96ff9b"
        },
        {
          "key": "JWT_SECRET",
          "value": "your_super_secret_jwt_key_change_this_in_production_12345"
        }
      ]
    }
  }
}